name: dart_codecov_generator
description: >
  Generates HTML lcov coverage reports for dart projects.(UNIX only)
  relies on:
  - coverage.dart (`pub global activate coverage`),
  - genhtml (part of lcov),
  - lsof (standard unix utility)
dependencies:
  args: any
dev_dependencies:
  coverage: '>=0.6.1 <0.7.0'
executables:
  generate_coverage:
