name: dart_codecov_generator
description: >
  Generates lcov or HTML coverage reports for Dart projects. (UNIX only)
dependencies:
  args: '>=0.13.0 <0.14.0'
  logging: '>=0.10.0 <0.11.0'
dev_dependencies:
  coverage:
    git:
      url: https://github.com/ekweible/coverage.git
      ref: master
  test: 0.12.0
dependency_overrides:
  logging: '>=0.10.0 <0.11.0'
executables:
  generate_coverage:
