name: dart_codecov_generator
version: 0.0.0
description: Generates lcov and/or HTML coverage reports for Dart projects. (UNIX only)
authors:
  - John Ryan
  - Evan Weible <ekweible@gmail.com>
homepage: https://github.com/ekweible/dart_codecov_generator
dependencies:
  args: '>=0.13.0 <0.14.0'
  logging: '>=0.9.0 <0.11.0'
dev_dependencies:
  coverage:
    git:
      url: https://github.com/ekweible/coverage.git
      ref: master
  dart_codecov:
    git:
      url: https://github.com/ekweible/dart_codecov.git
      ref: 0.1.0
  test: 0.12.0
dependency_overrides:
  coverage:
    git:
      url: https://github.com/ekweible/coverage.git
      ref: master
executables:
  generate_coverage:
