name: dart_codecov_generator_example
dev_dependencies:
  coverage:
    git:
      url: git@github.com:ekweible/coverage.git
      ref: master
  dart_codecov_generator:
    path: ..
  test: 0.12.0
dependency_overrides:
  logging: '>=0.10.0 <0.11.0'